name = "RiemannHilbert"
uuid = "79305c5b-9889-52e9-bdbd-56f883c71fe0"
version = "0.2.0"

[deps]
ClassicalOrthogonalPolynomials = "b30e2e7b-c4ee-47da-9d5f-2c5c27239acd"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
PowerNumbers = "7635a310-babe-11e9-2fde-a3dff3ddcf26"
RecurrenceRelationshipArrays = "b889d2dc-af3c-4820-88a8-238fa91d3518"
SingularIntegrals = "d7440221-8b5e-42fc-909c-0567823f424a"

[sources]
PowerNumbers = {path = "/Users/solver/Projects/PowerNumbers.jl"}
SingularIntegrals = {path = "/Users/solver/Projects/SingularIntegrals.jl/"}

[compat]
ClassicalOrthogonalPolynomials = "0.15"
HypergeometricFunctions = "0.3.30"
IntervalSets = "0.7.14"
PowerNumbers = "0.0.1"
RecurrenceRelationshipArrays = "0.1.5"
SingularIntegrals = "0.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
